String getAssessmentText(assessment) {
  if (assessment == 0) {
    return "This looks like it could be Actinic Keratosis: Actinic keratoses (also called solar keratoses) are dry scaly patches of skin that have been damaged by the sun.The patches are not usually serious. But there's a small chance they could become skin cancer, so it's important to avoid further damage to your skin. Check out our Skinformation section for more details.";
  } else if (assessment == 1) {
    return "This looks like it could be Basal Cell Carcinoma: Basal cell carcinoma (BCC) is the most common type of skin cancer, which develops in the top layer of the skin (epidermis). They usually grow slowly, and they rarely spread to other parts of the body.Basal cell carcinomas can occur anywhere on the body but are most common in areas that are exposed to the sun such as your face, head, neck, and ears.If left untreated, Basal cell carcinomas will continue to grow and can eventually cause an ulcer; hence they can have the name 'rodent ulcer'. They can start to destroy surrounding skin if they are left to continue to enlarge over time.Most Basal cell carcinomas are painless, although sometimes they can be itchy or bleed. Check out our skinformation section for more details.";
  } else if (assessment == 2) {
    return "This looks like it could be a benign keratosis lesion: A benign keratosis, commonly known as a Seborrheic Keratosis is a harmless skin growth. They are brown, black or light tan in colour and look waxy or scaly and slightly raised. Benign keratosis become more common as you age. Check out our skinformation section for more details.";
  } else if (assessment == 3) {
    return "This looks like it could be dematofibroma: A dermatofibroma is a common overgrowth of the fibrous tissue situated in the dermis (the deeper of the two main layers of the skin). It is benign (harmless) and will not turn into a cancer. Whilst dermatofibromas are harmless, they can be similar in appearance to other skin lesions like moles. Check out our skinformation section for more details.";
  } else if (assessment == 4) {
    return "This looks like it could be a melanoma: Melanoma is a type of skin cancer that can spread to other organs in the body. The most common sign of melanoma is the appearance of a new mole or a change in an existing mole. This can happen anywhere on the body, but the back, legs, arms and face are most commonly affected. In most cases, melanomas have an irregular shape and more than 1 colour. They may also be larger than normal moles and can sometimes be itchy or bleed. Check out our skinformation section for more details.";
  } else if (assessment == 5) {
    return "This looks like it could be a nevus: Nevus (plural: nevi) is the medical term for a mole. Nevi are very common. Most peopleTrusted Source have between 10 and 40. Common nevi are harmless collections of colored cells. They typically appear as small brown, tan, or pink spots. You can be born with moles or develop them later. Moles that you’re born with are known as congenital moles. However, most moles develop during childhood and adolescence. This is known as an acquired nevus. Moles can also develop later in life as a result of sun exposure. There are many types of nevi. Some of them are harmless and others more serious. Read on to learn about the different types and how to know whether you should get one checked out by your doctor. Check out our skinformation section for more details.";
  } else if (assessment == 6) {
    return "This looks like it could be a vascular lesion: Vascular lesions are relatively common abnormalities of the skin and underlying tissues, more commonly known as birthmarks. There are three major categories of vascular lesions: Hemangiomas, Vascular Malformations, and Pyogenic Granulomas. While these birthmarks can look similar at times, they each vary in terms of origin and necessary treatment. Check out our skinformation section for more details.";
  } else {
    return "Unable to assess condition of your skin. Try uploading different photo";
  }
}
